modLoader="javafml"
loaderVersion="[47,)" # Forge 1.20.1
license="All Rights Reserved"

[[mods]]
modId="discordauth"
version="1.0.0"
displayName="Discord Auth"
authors="messire"
description='''Авторизация игроков через Discord роль "игрок" на вашем сервере.'''

[[dependencies.discordauth]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.discordauth]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
